# Generated by Django 3.2.5 on 2021-07-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StudentStudiesRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=64)),
                ('carreer', models.CharField(max_length=128)),
                ('study_level', models.CharField(max_length=256)),
                ('carreer_progress', models.CharField(max_length=256)),
                ('programming_skills', models.IntegerField(verbose_name=[(1, 'None'), (2, 'Low'), (3, 'Medium'), (4, 'High')])),
                ('python_skills', models.IntegerField(verbose_name=[(1, 'None'), (2, 'Low'), (3, 'Medium'), (4, 'High')])),
            ],
        ),
    ]
