# Generated by Django 3.2.5 on 2021-07-27 22:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentStudiesRegistry',
            new_name='StudentStudiesRecord',
        ),
        migrations.DeleteModel(
            name='StudentRegistry',
        ),
    ]
