# Generated by Django 3.2.5 on 2021-08-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_studentrecord_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'First'), (2, 'Second')])),
                ('year', models.IntegerField()),
            ],
        ),
    ]
