# Generated by Django 3.2.5 on 2021-08-05 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_courserecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='app.courserecord'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='courserecord',
            unique_together={('quarter', 'year')},
        ),
    ]
