# Generated by Django 3.2.5 on 2021-08-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210805_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='studentrecord',
            unique_together={('email', 'course')},
        ),
    ]
