# Generated by Django 3.2.5 on 2021-08-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210810_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='studies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studies_records', to='app.studentstudiesrecord'),
            preserve_default=False,
        ),
    ]
