# Generated by Django 3.2.5 on 2021-08-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentrecord_studies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstudiesrecord',
            old_name='carreer',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='studentstudiesrecord',
            old_name='carreer_progress',
            new_name='career_progress',
        ),
    ]
