# Generated by Django 3.2.5 on 2021-08-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210817_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('business_name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='city',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='id_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='id_type',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentstudiesrecord',
            name='university_location',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job_records', to='app.studentjobrecord'),
            preserve_default=False,
        ),
    ]
