# Generated by Django 3.2.5 on 2021-08-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210819_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentjobrecord',
            name='location',
        ),
        migrations.RemoveField(
            model_name='studentstudiesrecord',
            name='career_progress',
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'First Quarter'), (2, 'Second Quarter')]),
        ),
    ]
