# Generated by Django 3.2.5 on 2021-11-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_studentrecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('unit', models.IntegerField()),
                ('accepts_pair_review', models.BooleanField()),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=128)),
                ('solution', models.FileField(blank=True, upload_to='uploads/')),
                ('unit_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unitsubmission')),
            ],
        ),
    ]
