# Generated by Django 3.2.5 on 2021-11-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_exercise_unitsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsubmission',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
