# Generated by Django 3.2.5 on 2021-11-29 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_unitsubmission_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='unit_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='app.unitsubmission'),
        ),
    ]
