# Generated by Django 3.2.5 on 2021-12-09 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='reviewer',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SelfEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_learning', models.IntegerField(choices=[])),
                ('exercises_autograde', models.IntegerField(choices=[])),
                ('dedication_in_hours', models.IntegerField(default=0)),
                ('dedication_evaluation', models.IntegerField(choices=[])),
                ('comment', models.TextField()),
                ('unit_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unitsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSelfEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exercise')),
                ('self_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.selfevaluation')),
            ],
        ),
    ]
