# Generated by Django 3.2.5 on 2021-12-20 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211209_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='code_presentation',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='correction',
            name='comment_for_author',
            field=models.CharField(blank=True, max_length=2056),
        ),
        migrations.AddField(
            model_name='correction',
            name='comment_for_teachers',
            field=models.CharField(blank=True, max_length=2056),
        ),
        migrations.AddField(
            model_name='correction',
            name='grade',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='correction',
            name='solves_exercise',
            field=models.IntegerField(choices=[(1, 'Tiene el ejercicio pedido'), (2, 'Tiene código pero no es el ejercicio pedido'), (3, 'Está vacío / No se puede abrir')], null=True),
        ),
        migrations.AddField(
            model_name='correction',
            name='tests',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Pocas veces'), (3, 'Si')], null=True),
        ),
        migrations.AddField(
            model_name='correction',
            name='works',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Pocas veces'), (3, 'Si')], null=True),
        ),
        migrations.AlterField(
            model_name='exerciseselfevaluation',
            name='grade',
            field=models.IntegerField(choices=[(1, 'No lo intenté'), (2, 'No entendí la consigna'), (3, 'No me salió'), (4, 'No estoy seguro/a'), (5, 'Me salió parcialmente'), (6, 'Me salió bien')]),
        ),
        migrations.AlterField(
            model_name='exerciseselfevaluation',
            name='self_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_self_evaluations', to='app.selfevaluation'),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='content_learning',
            field=models.IntegerField(choices=[(1, 'No entendi casi nada / no la leí'), (2, 'Me costó entender'), (3, 'Entendí casi todo'), (4, 'La segui sin problemas')]),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='dedication_evaluation',
            field=models.IntegerField(choices=[(1, 'Me pareció adecuado'), (2, 'Me llevó más tiempo del que me hubiera gustado dedicarle'), (3, 'Le podría haber dedicado más tiempo. Me sobró tiempo')]),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='exercises_autograde',
            field=models.IntegerField(choices=[(1, 'No hice ninguno'), (2, 'Me costaron mucho trabajo'), (3, 'En general me salieron bien'), (4, 'Los hice sin problemas')]),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='unit_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluations', to='app.unitsubmission'),
        ),
        migrations.CreateModel(
            name='CodeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity', models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')])),
                ('declarative', models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')])),
                ('modular', models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')])),
                ('reusable', models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')])),
                ('python', models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')])),
                ('commented', models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')])),
                ('correction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='app.correction')),
            ],
        ),
    ]
