# Generated by Django 3.2.5 on 2021-12-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211220_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='comment_for_author',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='comment_for_teachers',
            field=models.TextField(blank=True),
        ),
    ]
