# Generated by Django 3.2.5 on 2022-02-03 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211229_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseselfevaluation',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exerciseselfevaluation',
            name='exercise_name',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correction',
            name='code_presentation',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='correction',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
