# Generated by Django 3.2.5 on 2022-02-26 22:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220203_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='country',
            field=django_countries.fields.CountryField(max_length=128),
        ),
    ]
