# Generated by Django 3.2.5 on 2022-02-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_studentrecord_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='country',
            field=models.CharField(max_length=128),
        ),
    ]
