# Generated by Django 3.2.5 on 2022-03-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_studentrecord_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentjobrecord',
            name='business_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='studentjobrecord',
            name='position',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='state',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='career',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='study_level',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='university',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='university_location',
            field=models.CharField(max_length=512),
        ),
    ]
