# Generated by Django 3.2.5 on 2022-03-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220304_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='programming_skills',
            field=models.IntegerField(null=True, verbose_name=[(1, 'None'), (2, 'Low'), (3, 'Medium'), (4, 'High')]),
        ),
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='python_skills',
            field=models.IntegerField(null=True, verbose_name=[(1, 'None'), (2, 'Low'), (3, 'Medium'), (4, 'High')]),
        ),
    ]
