# Generated by Django 3.2.5 on 2022-03-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220304_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='id_number',
            field=models.CharField(max_length=64),
        ),
    ]
