# Generated by Django 3.2.5 on 2022-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_studentrecord_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsubmission',
            name='pair_review_comment',
            field=models.TextField(blank=True),
        ),
    ]
