# Generated by Django 3.2.5 on 2022-03-05 21:50

from django.db import migrations


def add_group_for_correctores(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Correctores")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_unitsubmission_pair_review_comment'),
    ]

    operations = [
        migrations.RunPython(add_group_for_correctores)
    ]
