# Generated by Django 3.2.5 on 2022-03-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_datamigration_add_group_for_correctores'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
