# Generated by Django 3.2.5 on 2022-03-06 21:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_correction_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='code_presentation',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Presentación del código'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='comment_for_author',
            field=models.TextField(blank=True, verbose_name='Comentario para autor'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='comment_for_teachers',
            field=models.TextField(blank=True, verbose_name='Comentario para docentes'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Corregido'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='app.exercise', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='reviewer',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to=settings.AUTH_USER_MODEL, verbose_name='Corrector'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='solves_exercise',
            field=models.IntegerField(choices=[(1, 'Tiene el ejercicio pedido'), (2, 'Tiene código pero no es el ejercicio pedido'), (3, 'Está vacío / No se puede abrir')], null=True, verbose_name='Resuelve ejercicio'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='tests',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Pocas veces'), (3, 'Si')], null=True, verbose_name='Tiene tests?'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='works',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Pocas veces'), (3, 'Si')], null=True, verbose_name='Funciona?'),
        ),
    ]
