# Generated by Django 3.2.5 on 2022-03-06 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0028_auto_20220306_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserecord',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'First Quarter'), (2, 'Second Quarter')], verbose_name='Cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='solution',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Solución'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='unit_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='app.unitsubmission', verbose_name='Entrega de Unidad'),
        ),
        migrations.AlterField(
            model_name='exerciseselfevaluation',
            name='exercise_name',
            field=models.CharField(max_length=128, verbose_name='Nombre del Ejercicio'),
        ),
        migrations.AlterField(
            model_name='exerciseselfevaluation',
            name='grade',
            field=models.IntegerField(choices=[(1, 'No lo intenté'), (2, 'No entendí la consigna'), (3, 'No me salió'), (4, 'No estoy seguro/a'), (5, 'Me salió parcialmente'), (6, 'Me salió bien')], verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='exerciseselfevaluation',
            name='self_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_self_evaluations', to='app.selfevaluation', verbose_name='Autoevaluación'),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='comment',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='content_learning',
            field=models.IntegerField(choices=[(1, 'No entendi casi nada / no la leí'), (2, 'Me costó entender'), (3, 'Entendí casi todo'), (4, 'La segui sin problemas')], verbose_name='Sobre los contenidos'),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='dedication_evaluation',
            field=models.IntegerField(choices=[(1, 'Me pareció adecuado'), (2, 'Me llevó más tiempo del que me hubiera gustado dedicarle'), (3, 'Le podría haber dedicado más tiempo. Me sobró tiempo')], verbose_name='Sobre la dedicación'),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='dedication_in_hours',
            field=models.IntegerField(default=0, verbose_name='Dedicación en horas'),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='exercises_autograde',
            field=models.IntegerField(choices=[(1, 'No hice ninguno'), (2, 'Me costaron mucho trabajo'), (3, 'En general me salieron bien'), (4, 'Los hice sin problemas')], verbose_name='Sobre los ejercicios'),
        ),
        migrations.AlterField(
            model_name='selfevaluation',
            name='unit_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluations', to='app.unitsubmission', verbose_name='Entrega de Unidad'),
        ),
        migrations.AlterField(
            model_name='studentjobrecord',
            name='business_name',
            field=models.CharField(max_length=512, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='studentjobrecord',
            name='position',
            field=models.CharField(max_length=512, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='city',
            field=models.CharField(max_length=256, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='country',
            field=models.CharField(max_length=128, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='app.courserecord', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='id_number',
            field=models.CharField(max_length=64, verbose_name='Nro Documento'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='id_type',
            field=models.CharField(max_length=64, verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_records', to='app.studentjobrecord', verbose_name='Trabajo'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='state',
            field=models.CharField(max_length=256, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='studies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies_records', to='app.studentstudiesrecord', verbose_name='Estudios'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='surname',
            field=models.CharField(max_length=64, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='career',
            field=models.CharField(max_length=512, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='study_level',
            field=models.CharField(max_length=512, verbose_name='Nivel de Estudio'),
        ),
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='university',
            field=models.CharField(max_length=512, verbose_name='Universidad'),
        ),
        migrations.AlterField(
            model_name='studentstudiesrecord',
            name='university_location',
            field=models.CharField(max_length=512, verbose_name='Locación universidad'),
        ),
        migrations.AlterField(
            model_name='unitsubmission',
            name='accepts_pair_review',
            field=models.BooleanField(verbose_name='Acepta Revisión entre Pares'),
        ),
        migrations.AlterField(
            model_name='unitsubmission',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='unitsubmission',
            name='pair_review_comment',
            field=models.TextField(blank=True, verbose_name='Comentario Revisión entre Pares'),
        ),
        migrations.AlterField(
            model_name='unitsubmission',
            name='student_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentrecord', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='unitsubmission',
            name='unit',
            field=models.IntegerField(verbose_name='Unidad'),
        ),
    ]
