# Generated by Django 3.2.5 on 2022-03-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220306_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeevaluation',
            name='clarity',
            field=models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')], verbose_name='Claridad'),
        ),
        migrations.AlterField(
            model_name='codeevaluation',
            name='commented',
            field=models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='codeevaluation',
            name='correction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='app.correction', verbose_name='Corrección'),
        ),
        migrations.AlterField(
            model_name='codeevaluation',
            name='declarative',
            field=models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')], verbose_name='Declaratividad'),
        ),
        migrations.AlterField(
            model_name='codeevaluation',
            name='modular',
            field=models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')], verbose_name='Modular'),
        ),
        migrations.AlterField(
            model_name='codeevaluation',
            name='python',
            field=models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')], verbose_name='Python'),
        ),
        migrations.AlterField(
            model_name='codeevaluation',
            name='reusable',
            field=models.IntegerField(choices=[(1, 'Nop!'), (2, 'Un poco'), (3, 'Normal'), (4, 'Muy bien'), (5, 'Genial!')], verbose_name='Reusable'),
        ),
    ]
