# Generated by Django 3.2.5 on 2022-03-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20220306_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeevaluation',
            options={'verbose_name': 'Evaluación del código', 'verbose_name_plural': 'Evaluaciones de código'},
        ),
        migrations.AlterModelOptions(
            name='correction',
            options={'verbose_name': 'Corrección', 'verbose_name_plural': 'Correcciones'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='exerciseselfevaluation',
            options={'verbose_name': 'Autoevaluación de ejercicio', 'verbose_name_plural': 'Autoevaluaciones de ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='selfevaluation',
            options={'verbose_name': 'Autoevaluación', 'verbose_name_plural': 'Autoevaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='studentjobrecord',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AlterModelOptions(
            name='studentrecord',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='studentstudiesrecord',
            options={'verbose_name': 'Estudio', 'verbose_name_plural': 'Estudios'},
        ),
        migrations.AlterModelOptions(
            name='unitsubmission',
            options={'verbose_name': 'Entrega de Unidad', 'verbose_name_plural': 'Entregas de Unidades'},
        ),
    ]
