# Generated by Django 3.2.5 on 2022-03-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220306_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='correction_time_in_minutes',
            field=models.PositiveIntegerField(null=True, verbose_name='Tiene utilizado para corregir (en minutos)'),
        ),
    ]
