# Generated by Django 3.2.5 on 2022-03-12 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0032_correction_correction_time_in_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairReviewCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_for_author', models.TextField(blank=True, verbose_name='Comentario para autor')),
                ('done', models.BooleanField(default=False, verbose_name='Corregido')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pair_review_correction', to='app.exercise', verbose_name='Ejercicio')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_review_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Corrector')),
            ],
            options={
                'verbose_name': 'Revisión de pares',
                'verbose_name_plural': 'Revisiones de pares',
            },
        ),
    ]
