# Generated by Django 3.2.5 on 2022-03-12 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_pairreviewcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairreviewcorrection',
            name='correction_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Entrega'),
            preserve_default=False,
        ),
    ]
