# Generated by Django 3.2.5 on 2022-03-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_pairreviewcorrection_correction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairreviewcorrection',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_review_corrections', to='app.studentrecord', verbose_name='Corrector'),
        ),
    ]
