# Generated by Django 3.2.5 on 2022-03-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_pairreviewcorrection_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairreviewcorrection',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
