# Generated by Django 3.2.5 on 2022-03-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_pairreviewcorrection_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthomaticCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('done', models.BooleanField(default=False, verbose_name='Corregido')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authomatic_correction', to='app.exercise', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Corrección automática',
                'verbose_name_plural': 'Correcciones automáticas',
            },
        ),
    ]
