# Generated by Django 3.2.5 on 2022-03-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_authomaticcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairreviewcorrection',
            name='is_anonymous_reviewer',
            field=models.BooleanField(default=True, verbose_name='Corrector Anonimo?'),
        ),
    ]
