# Generated by Django 3.2.5 on 2022-04-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_pairreviewcorrection_is_anonymous_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairreviewcorrection',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_review_correction', to='app.exercise', verbose_name='Ejercicio'),
        ),
    ]
