# Generated by Django 3.2.5 on 2022-04-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_pairreviewcorrection_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='authomaticcorrection',
            name='correct_tests_percentage',
            field=models.FloatField(default=0, verbose_name='Porceporntaje de tests correctos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authomaticcorrection',
            name='errors',
            field=models.TextField(default='[]', verbose_name='Listado de errores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authomaticcorrection',
            name='evaluated_code',
            field=models.TextField(default='', verbose_name='Codigo evaluado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authomaticcorrection',
            name='executed_instruction',
            field=models.CharField(default='', max_length=2056, verbose_name='Ejecucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authomaticcorrection',
            name='recommendations',
            field=models.TextField(default='[]', verbose_name='Listado de Recomendaciones'),
            preserve_default=False,
        ),
    ]
