# Generated by Django 3.2.5 on 2022-04-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20220407_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authomaticcorrection',
            name='done',
        ),
    ]
