# Generated by Django 3.2.5 on 2022-04-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_authomaticcorrection_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='authomaticcorrection',
            name='is_original',
            field=models.BooleanField(default=True, verbose_name='Es original?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authomaticcorrection',
            name='worked',
            field=models.BooleanField(default=True, verbose_name='Funciona?'),
            preserve_default=False,
        ),
    ]
