# Generated by Django 3.2.5 on 2022-04-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20220411_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authomaticcorrection',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authomatic_correction', to='app.exercise', verbose_name='Ejercicio'),
        ),
    ]
