# Generated by Django 3.2.5 on 2022-04-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_authomaticcorrection_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authomaticcorrection',
            name='correct_tests_percentage',
            field=models.FloatField(verbose_name='Porcentaje de tests correctos'),
        ),
    ]
